name: CMake Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure Project
      run: |
        mkdir -p ${{github.workspace}}/build
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build Project
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }} --parallel

    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ${{github.workspace}}/build
        ctest --output-on-failure
